### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [BitTheByte/FacebookCracker#2]
hello sir thank you for the good script but i want more help for other script cracker login page for something like that

http://118.69.246.160:8080/admin/config.php
username : admin
password : admin

i want great script for cracking login page for this type with multi threading and multiprocessing

thank you

**Comment by BitTheByte** [comment]
Hi @VoipSip 

First, Typing credentials for an admin panel violates [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines). Secound, I **DO NOT** under any circumstances (even if paid) provide cracking/hacking/spam tools whither it's for individuals or companies

Thanks
